#!/bin/sh

# Change your keymap:
xmodmap "$HOME/.xmodmaprc"

# turn off caps lock, have never needed it.
setxkbmap -option ctrl:nocaps &

# Setting the locale here to make fluxbox and everything it starts
# aware of my preferred locale (setting it in .bashrc is sometimes too
# late).
export LC_ALL=en_GB.utf8
exec fluxbox -log ~/.fluxbox/log

