#!/bin/sh

# Change your keymap:
xmodmap "/home/torstein/.xmodmaprc"

# suspect unclutter makes X crash/reset after locking when using
# external, portrait monitor with the nVIDIA drivers. (2013-01-10).
# unclutter -idle 2 &

# turn off caps lock, have never needed it.
setxkbmap -option ctrl:nocaps &

# turn off bell
xset -b

# wallpaper
# display -window root ~/pictures/wallpaper &

# favourite applications
app_list="
  clipit
  conky
  davmail
"
for app in ${app_list}; do
  if [ -x /usr/bin/${app} ]; then
      ${app} &
  fi
done

# gnome-power-manager &
killall -9 gnome-screensaver
xscreensaver &

# touch /tmp/dates
# root-tail -i 20 -fn 7x14 -g 400x60+0+740 /tmp/dates &
# root-tail -i 20 -fn 7x14 -g 400x20+900+780 /tmp/current-music &

# Setting the locale here to make fluxbox and everything it starts
# aware of my preferred locale (setting it in .bashrc is sometimes too
# late).
export LC_ALL=en_GB.utf8
exec fluxbox -log ~/.fluxbox/log
