#! /usr/bin/env bash

header_file=$(dirname $0)/header.html
footer_file=$(dirname $0)/footer.html

output_file=$(mktemp)
src_dir=$HOME/src/skybert-net/src
target_dir=$(echo $src_dir | sed 's/src$/target/')
echo $target_dir


cat $header_file > $output_file
sed -f $(dirname $0)/$(basename $0).sed $1 >> $output_file
cat $footer_file >> $output_file


function create_file_name() {
  echo ""
}

function fix_title() {
  title=$(sed -n 's/^#+TITLE: \(.*\)/\1/p' $1)
  sed -i "s~<title>\(.*\)</title>~<title>${title}</title>~" $output_file
}

function get_title_fn() {
  echo "$title" | tr '[A-Z]' '[a-z]' | \
    sed 's/[,!?_ ]/-/g'
}

fix_title $1
final_fn=${target_dir}/$(get_title_fn).html
cat $output_file | xml_pp | xmllint --format - > $final_fn
rm $output_file
echo $final_fn "is now ready"
