#! /usr/bin/env bash

header_file=$(dirname $0)/header.html
footer_file=$(dirname $0)/footer.html

output_file=$(mktemp)
cat $header_file > $output_file
sed -f $(dirname $0)/$(basename $0).sed $1 >> $output_file
cat $footer_file >> $output_file


function create_file_name() {
  echo ""
}

function fix_title() {
  local title=$(sed -n 's/^#+TITLE: \(.*\)/\1/p' $1)
  sed -i "s~<title>\(.*\)</title>~<title>${title}</title>~" $output_file
}


fix_title $1
cat $output_file | xml_pp | xmllint --format -
rm $output_file
