#! /usr/bin/env bash

# by torstein.k.johansen@gmail.com
set -e
set -u
set -o pipefail

p4_src=~/src/p4/escenic
l="
model-core
core
common
engine
studio
engine-dist"



main() {
  local days=${1-1}
  if [[ ! $days =~ ^[0-9]*$ ]]; then
    echo "Usage: $(basename $0) <number-of-days>"
    exit 1
  fi

  local from_date=$(date +%Y/%m/%d --date @$(( $(date +%s) - (${days-1} * 24 * 60 * 60))))
  # to_date to tomorrow to include today's commits
  local to_date=$(date +%Y/%m/%d --date @$(( $(date +%s) + (24 * 60 * 60))))

  echo "Changed from ${from_date} to ${to_date}:"

  for el in ${l}; do
    local p4_path=${p4_src}/${el}/trunk/...
    echo "→ ${p4_path}"
    p4 changes -l ${p4_path}@${from_date},${to_date};
  done
}

main "$@"
