#! /usr/bin/env bash

# by tkj@vizrt.com

if [ $(which identify 2>/dev/null | wc -l) -eq 0 ]; then
  echo "You need ImageMagick installed to use $(basename $0) :-("
  exit 1
fi

cat <<EOF
Press ENTER to convert all images in the current directory and all sub
directories to standard RGB colour space if they're currently CMYK.

To abort, press Ctrl + c now.
EOF
read answer

function get_picture_file_list() {
  find -L . \
    -iname "*.jpg" -o \
    -iname "*.jpeg" -o \
    -iname "*.png" -o \
    -iname "*.gif"
}

picture_list=$(get_picture_file_list)
echo "Total number of pictures in $(pwd):" $(echo "$pictures" | wc -l)

current_picture=0

for f in $picture_list; do
  current_picture=$(( $current_picture + 1 ))
  if [ ! -s "$f" ]; then
    echo "Picture #${current_picture} is empty: $f"
    continue
  fi
  
  if [ $(identify -verbose "$f" | \
    grep Colorspace | \
    grep CMYK | wc -l) -gt 0 ]; then
    echo "Picture #${current_picture} uses CMYK color profile," \
      "converting it to RGB ..."
    (
      cd $(dirname "$f")
      file=$(basename "$f")
      convert "$file" -colorspace rgb "$file"
    )
  fi
done
