#! /usr/bin/env bash

# by torstein.k.johansen@gmail.com

su -c wired
get-new-email &
tkj setup-screens &
tkj daily

# something runs fbsetbg which fails because of change in screen setup
killall xmessage || true

