#! /usr/bin/env bash

# Unit testing for BASH
# by torstein.k.johansen@gmail.com

source alexandria

show_positives=0

# $1 message
# $2 expected
# $3 actual
function assert_equals()
{
    local message=$1
    local expected=$2
    local actual=$3
    
    if [ $# -eq 2 ]; then
        local message=""
        local expected=$1
        local actual=$2
    fi

    if [[ $(is_number $expected) -eq 1 && $(is_number $actual) -eq 1 ]]; then
        if [ $expected -ne $actual ]; then
            echo "FAILED: ${message}: Expected <$expected>, but was <$actual>"
        elif [ $show_positives -eq 1 ]; then
            echo "PASSED: ${message}: Expected <$expected> and got <$actual>"
        fi
    else
        if [ "$expected" != "$actual" ]; then
            echo "FAILED: ${message}: Expected <$expected>, but was <$actual>"
        elif [ $show_positives -eq 1 ]; then
            echo "PASSED: ${message}: Expected <$expected> and got <$actual>"
        fi
    fi
}

function assert_null()
{
    local message=$1
    local value=$2
    
    if [ -z "$(eval echo $`echo $value`)" ]; then
        if [ $show_positives -eq 1 ]; then
            echo "PASSED: ${message}: <$value> is null (unset)"
        fi
    else
        echo "FAILED: ${message}: <$value> is not null (it is set)"
    fi
}

function assert_not_null()
{
    local message=$1
    local value=$2

    if [ -n "$(eval echo $`echo $value`)" ]; then
        if [ $show_positives -eq 1 ]; then
            echo "PASSED: ${message}: <$value> is not null (it is set)"
        fi
    else
        echo "FAILED: ${message}: <$value> is null (it is not set)"
    fi
}


