#! /usr/bin/env bash

# makes files and directory names beautiful.

echo "Press ENTER to beatify files from $(pwd) and beyond, Ctrl-c to abort."
echo -n "You choose> " 
read ok

find . | while read f; do
    if [ "$f" = "." -o "$f" = ".." ]; then
        continue
    elif [ $(echo "$f" | grep [A-Z] | wc -l) -eq 0 -o \
        $(echo "$f" | grep " " | wc -l) -eq 0 ]; then
        continue
    fi
    
    beautiful_name=$(echo "$f" | sed -e 's/\ /_/g' | tr [A-Z] [a-z])
    mv "$f" "$beautiful_name"
done

