#! /usr/bin/env bash

# makes files and directory names beautiful.
#
# by torstein.k.johansen@gmail.com

if [[ "$1" != "-q" ]]; then
  echo "Press ENTER to beatify files in $(pwd), Ctrl-c to abort."
  echo -n "You choose> " 
  read ok
fi

find . -maxdepth 1 | while read f; do
    if [ "$f" = "." -o "$f" = ".." ]; then
        continue
    fi
    beautiful_name=$(echo "$f" | \
        sed \
        -e 's/\ /_/g' \
        -e 's/&/_/g' \
        -e 's/{/_/g' \
        -e 's/}/_/g' \
        -e 's/)/_/g' \
        -e 's/(/_/g' \
        -e 's/\]/_/g' \
        -e 's/\[/_/g' \
        | \
        tr [A-Z] [a-z])

    if [[ "$f" == "$beautiful_name" ]]; then
      continue
    fi
    
    echo "Beautifying $f -> $beautiful_name"
    mv "$f" "$beautiful_name"
done
