#! /usr/bin/env bash

# by torstein.k.johansen@gmail.com

set -o errexit
set -o nounset
set -o pipefail

source ~/src/moria/src/common/text/color.sh
source ~/src/moria/src/common/indispensable.sh
source ~/src/moria/src/common/common-exit-hook.sh

git_url=http://git.sv.gnu.org/r/emacs.git
src=/usr/local/src/emacs

checkout_or_update_repository() {
  print "${FUNCNAME[0]} ..."
  if [ -e "${src}" ]; then
    (
      run cd "${src}"
      run git checkout master
      run git pull origin master
    )
  else
    run git clone "${git_url}" "${src}"
  fi

  local branch=${1-master}
  run cd "${src}"
  run git checkout "${branch}"
  print "${FUNCNAME[0]} branch=${branch} ..."

  # creating machine dependent build files
  aclocal
  autoheader
  automake --force-missing --add-missing
  autoconf
}

compile() {
  print "${FUNCNAME[0]} ..."
  run cd "${src}"
  run make clean
  run sh ./autogen.sh
  run sh ./autogen.sh git
  run ./configure \
      CFLAGS=-no-pie \
      --with-x-toolkit=gtk \
      --with-png \
      --with-jpeg \
      --with-gif
  run nice -n 19 make
  print "Compile was successful, now enter your root password to install it."
  su -c "make install"
}


main() {
  print "${FUNCNAME[0]} ..."
  checkout_or_update_repository  "${1-master}"
  compile
}

main "$@"
