#! /usr/bin/env bash

# by torstein.k.johansen@gmail.com

set -o errexit
set -o nounset
set -o pipefail

source ~/src/moria/src/common/text/color.sh
source ~/src/moria/src/common/indispensable.sh
source ~/src/moria/src/common/common-exit-hook.sh

git_url=http://git.sv.gnu.org/r/emacs.git
src=/usr/local/src/emacs

checkout_or_update_repository() {
  print "$FUNCNAME ..."
  if [ -e "${src}" ]; then
    (
      run cd "${src}"
      run git checkout master
      run git pull origin master
    )
  else
    run git clone "${git_url}" "${src}"

    # creating machine dependent build files
    run cd "${src}"
    aclocal
    autoheader
    automake --force-missing --add-missing
    autoconf
  fi
}

compile() {
  local branch=$1

  run git checkout ${branch-master}
  print "$FUNCNAME branch=${branch} ..."
  run cd "${src}"
  run make clean
  run ./configure \
    --with-x-toolkit=gtk \
    --with-png \
    --with-jpeg \
    --with-gif
  run make
  print "Compile was successful, now enter your root password to install it."
  su -c "make install"
}


main() {
  print "$FUNCNAME ..."
  checkout_or_update_repository
  compile $1
}

main "$@"
