#! /usr/bin/env bash

# by torstein.k.johansen@gmail.com
set -o errexit
set -o nounset
set -o pipefail

source ~/src/moria/src/common/text/color.sh
source ~/src/moria/src/common/indispensable.sh
source ~/src/moria/src/common/common-exit-hook.sh

conf_file=$HOME/.$(basename $0).conf
log_file=$HOME/.$(basename $0).log

read_user_input() {
  src_file=$1
}

main() {
  read_user_input "$@"

  pandoc \
    --standalone \
    -f markdown \
    --variable revealjs-url=../reveal.js \
    --variable transition=slide \
    --template ../escenic.revealjs.template \
    -t revealjs \
    -o index.html \
    ${src_file}
}

main "$@"
