#! /usr/bin/env bash

# torstein.k.johansen@gmail.com

# Creates the file cache I use with the file-cache and ido-mode Emacs
# modules.

dir_list="
$HOME/.emacs.d
$HOME/src/my-little-friends
$HOME/src/DocEngine
$HOME/src/VLAN-MAN
"
file_list="
$HOME/src/my-little-friends/bash/create-emacs-file-cache
$HOME/.bashrc
$HOME/.emacs
"

file=~/.emacs.d/file_cache.el

echo "Generating new file cache $file"
echo "(" > $file

# add .java files
function create_entry() {
	echo "(\""$(basename $1)"\" \""$(dirname $1)"/\")"
}

for suffix in java properties sh org vcl; do
  find $dir_list -name "*.${suffix}" 2>/dev/null | while read f; do
    create_entry $f >> $file
  done
done

echo ")" >> $file

echo "Done, $file is now ready"
