#! /usr/bin/env bash

# torstein.k.johansen@gmail.com

# Creates the file cache I use with the file-cache and ido-mode Emacs
# modules.

dir_list="
$HOME/.emacs.d
$HOME/src/ece-scripts
$HOME/src/my-little-friends
$HOME/src/nie/trunk
$HOME/src/solartv
$HOME/doc
$HOME/src/p4/escenic/common/trunk
$HOME/src/p4/escenic/engine/trunk
$HOME/src/p4/escenic/model-core/trunk
$HOME/src/p4/escenic/plugins/analysis/trunk
$HOME/src/p4/escenic/plugins/community/trunk
$HOME/src/p4/escenic/plugins/dashboard/trunk
$HOME/src/p4/escenic/plugins/forum/trunk
$HOME/src/p4/escenic/plugins/viziwyg/trunk
$HOME/src/p4/escenic/studio/trunk
"
file_list="
$HOME/.bashrc
$HOME/.emacs
"

file=~/.emacs.d/file_cache.el

echo "Generating new file cache $file"
echo "(" > $file

# add .java files
function create_entry() {
	echo "(\""$(basename $1)"\" \""$(dirname $1)"/\")"
}

for suffix in java properties sh org; do
  find $dir_list -name "*.${suffix}" | while read f; do
    create_entry $f >> $file
  done
done

find $HOME/src/ece-scripts/usr/bin \
  $HOME/src/ece-scripts/usr/sbin \
  $HOME/src/my-little-friends/bash \
  -type f | while read f; do
  create_entry $f >> $file
done

echo ")" >> $file

echo "Done, $file is now ready"

