#! /usr/bin/env bash

# by torstein.k.johansen at gmail dot com

# call the script with the CSV from Thunderbird's Addressbook export
# and the output file (typically $HOME/.mailrc)
# create-mail-alias-from-tb-csv export-from-thunderbird.csv $HOME/.mailrc

echo "Using $1 to create UNIX mail aliases in $2"

cat $1 | sort | while read f; do
    if [ $(echo $f | grep "@" | wc -l) -lt 1 ]; then
        continue
    fi
    
    name=$(echo $f | cut -d',' -f1 | sed 's/ /\./g' | tr [A-Z] [a-z])
    email=$(echo $f | cut -d',' -f5 | tr [A-Z] [a-z])

    if [ -z "${name}" ]; then
	name=$(echo $email | cut -d'@' -f1)
    fi
    
    echo alias $name $email >> $2
done
