#! /usr/bin/env bash

# Get the IP of container with name
#
# by torstein@escenic.com

container_name=$1
docker \
  inspect \
  --format='{{range $net, $conf := .NetworkSettings.Networks}}{{$conf.IPAddress}} {{end}}' \
  $(docker ps -qf name="${container_name}")
