#! /usr/bin/env bash

# by tkj@vizrt.com

function get_versions_declared_explicitly()
{
    # filtering out escenic & mobiletech dependencies
    echo -e "$(xml_grep --nowrap --cond project/dependencies/dependency $el | \
        sed 's#/dependency><#/dependency>\n<#g' | \
        grep -v com.escenic | \
        grep -v mobiletech | \
        grep version | \
        grep -v '\$')"
}

if [ $1 ]; then
    filter=$1
else
    filter=pom.xml
fi

for el in `find -name pom.xml | egrep -v "osl|dhk|target" | grep "$filter"`; do
    versions=$(get_versions_declared_explicitly ${el})
    if [ -n "$versions" ]; then
        version_in_file=$(echo ${versions} | sed -e "s#.*<version>\([a-z0-9\.-]*\)</version>.*#\1\n#g")
        for ele in "${version_in_file}"; do
            grep -H -n ">${ele}<" ${el} | grep -v trunk-SNAPSHOT | grep -v '\$'
        done
    fi        
done

exit 0
