#! /usr/bin/env bash

function get_xml_pp()
{
    local xml_pretty_printer=""
    
    if [ $(which xml_pp 2>/dev/null | wc -l) -gt 0 ]; then
        xml_pretty_printer=xml_pp
    elif [ $(which xmllint 2>/dev/null | wc -l) -gt 0 ]; then
        xml_pretty_printer="xmllint --format -"
    fi

    echo "$xml_pretty_printer"
}

xml_pretty_printer=$(get_xml_pp)
curl -s $1 | sed "s/></>\n</g" | $xml_pretty_printer







