#! /usr/bin/env bash

## Command for running all the PMD tests I want, outputting the results
## in Emacs friendly format so that it can be picked up by e.g. compile
## mode or flymake.
## 
## by torstein.k.johansen@conduct.no

pmd_home=/opt/pmd
$pmd_home/bin/run.sh \
  pmd \
  -f emacs \
  -rulesets java-basic,java-braces,java-clone,java-codesize,java-comments,java-controversial,java-coupling,java-design,java-empty,java-finalizers,java-imports,java-j2ee,java-javabeans,java-junit,java-logging-jakarta-commons,java-logging-java,java-migrating,java-naming,java-optimizations,java-strictexception,java-strings,java-sunsecure,java-typeresolution,java-unnecessary,java-unusedcode \
  -encoding UTF-8 \
  -d "$@" 
