#! /usr/bin/env bash

## Runs your desired test. This is just a glorified BASH alias
##
## by torstein

print_usage() {
    cat <<EOF
Usage: $(basename $0) <java unit test>

Runs your desired test. This is just a glorified BASH alias

Examples:
$(basename $0) MyTest
$(basename $0) MyTest#myTestMethod
EOF
}

show_test_report() {
    if [ ${show_test_report-1} -eq 1 ]; then
        local report=$(find target/surefire-reports -name *${1}.txt)

        if [[ -r "$report" && $(cat "$report" | wc -l) -gt 4 ]]; then
            cat $report
        fi
    fi
}

main() {
    clear
    echo "Running test" $1 "..."
    mvn -o -q compile test -Dtest=$1
    show_test_report $1
}

if [ $# -lt 1 ]; then
    print_usage
    exit 1
fi

main $@
