#! /usr/bin/env bash

## Runs your desired test. This is just a glorified BASH alias
##
## by torstein

print_usage() {
    cat <<EOF
Usage: $(basename $0) <java unit test>

Runs your desired test. This is just a glorified BASH alias

Examples:
$(basename $0) MyTest
$(basename $0) MyTest#myTestMethod
EOF
}

main() {
    clear
    mvn -o -q test -Dtest=$1
}

if [ $# -lt 1 ]; then
    print_usage
    exit 1
fi

main $@
