#! /usr/bin/env bash

install_base_dir=/opt
eclipse_home=/opt/eclipse
ext_src_base_dir=/usr/local/src
# 2.2.5 matches the latest Eclipse Juno release
# eclim_tag=2.2.5

function run() {
  "$@"
  if [ $? -gt 0 ]; then
    echo "The command <$@> failed :-("
    exit 1
  fi
}

function set_up_emacs_eclim() {
  echo "Setting up/updating emacs-eclim ..."
  if [ ! -d $ext_src_base_dir/emacs/emacs-eclim ]; then
    run mkdir -p $ext_src_base_dir/emacs
    run cd $ext_src_base_dir/emacs
    run git clone https://github.com/senny/emacs-eclim.git
  else
    run cd $ext_src_base_dir/emacs/emacs-eclim
    run git pull --rebase
  fi
}

function set_up_eclim() {
  echo "Setting/updating up eclim ..."
  if [ ! -d $ext_src_base_dir/eclim ]; then
    run mkdir -p $ext_src_base_dir
    run cd $ext_src_base_dir
    run git clone https://github.com/ervandew/eclim.git
  fi
  run cd $ext_src_base_dir/eclim
  run git pull --rebase

  if [ ! -d $eclipse_home ]; then
    echo "You need to install Eclipse in" $eclipse_home
    exit 1
  fi
  run ant -Declipse.home=${eclipse_home}
}

set_up_eclim
set_up_emacs_eclim
