#! /usr/bin/env bash

# simple script for getting a full the time of a full PI. Works only
# on sites that haven't added robot exclusion files. If you control
# the server, be sure to let your test script pull down all the
# resources.
#
# tkj/at/freeshell/dot/org

if [ ! $1 ]; then
  echo "You must pass a URL: $(basename $0) http://example.com"
  exit 1
fi

time wget -p --delete-after $1 -o /dev/null



